### ISSUE TITLE
“GraphvizDotConvertor” only support Windows

### ISSUE THREAD

**Issue by mumutu66** [sbellus/fitnesse-graphviz-plugin#1]
hard code  seems only support windows platform.  I think it should be switched with the os.name 
``` 
  runner = Runtime.getRuntime().exec(
                    new String[] { "cmd.exe", "/c", dotExecutable, "-Tsvg", dotFile.getName() }, null,
                    new File(dotPath));
```

**Comment by sbellus** [comment]
Thanks.
I will do it tomorrow.

Typed with thumbs.

**Comment by sbellus** [comment]
Please check the new release [Release 1.2](https://github.com/sbellus/fitnesse-graphviz-plugin/releases/tag/1.2) and give me the feedback.

Thanks.
