### ISSUE TITLE
ClassNotFoundException: org.apache.commons.lang.SystemUtils

### ISSUE THREAD

**Issue by CHeuberger** [sbellus/fitnesse-graphviz-plugin#2]
When starting the server the `ClassNotFoundException: org.apache.commons.lang.SystemUtils` is thrown (see stack trace below).

Fitnesse:  `fitnesse-standalone.jar` v20190119 
Plugin: [Release 1.2](https://github.com/sbellus/fitnesse-graphviz-plugin/releases/tag/1.2)
Graphviz: 2.38

The Fitnesse JAR includes `org.apache.commons.lang3.SystemUtils` instead of the missing class, that is, package `lang3` and not `lang` (was included in some previous version, I think v2016* .)

**Workaround**: set the path to the executable is the properties file as described in the projects [`Readme.md`](https://github.com/sbellus/fitnesse-graphviz-plugin/blob/master/README.md).

**Fix**: probably just adjust the package name in `GraphvizDotFinder`.

##### Full Stack Trace
 
> ```
> java version "1.8.0_141"
> Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
> Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)
> 
> Exception in thread "main" java.util.ServiceConfigurationError: fitnesse.plugins.PluginFeatureFactory: Provider com.github.sbellus.fitnesse.graphviz.GraphvizPlugin could not be instantiated
> 	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
> 	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
> 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
> 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
> 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
> 	at fitnesse.plugins.PluginsLoader.findPluginFeatureFactories(PluginsLoader.java:43)
> 	at fitnesse.plugins.PluginsLoader.<init>(PluginsLoader.java:36)
> 	at fitnesse.ContextConfigurator.makeFitNesseContext(ContextConfigurator.java:117)
> 	at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:72)
> 	at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:59)
> 	at fitnesseMain.FitNesseMain.main(FitNesseMain.java:39)
> Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/SystemUtils
> 	at com.github.sbellus.fitnesse.graphviz.GraphvizDotFinder.findDot(GraphvizDotFinder.java:14)
> 	at com.github.sbellus.fitnesse.graphviz.GraphvizPlugin.makeProperties(GraphvizPlugin.java:47)
> 	at com.github.sbellus.fitnesse.graphviz.GraphvizPlugin.<init>(GraphvizPlugin.java:21)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at java.lang.Class.newInstance(Class.java:442)
> 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
> 	... 8 more
> Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.SystemUtils
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 17 more
> ```

**Comment by sbellus** [comment]
Thanks for reporting.

Should be fixed in Release 1.3.
